### PR TITLE
Update POSTGIS_VERSION

### PR DESCRIPTION
**Pull request by rick**
image

Upstream version has moved on, updating.

### CODE REVIEW

**Comment by md5** [comment]
Do you mind running "make update" to update all the Dockerfiles?

**Comment by rick** [comment]
Done! ☑️

**Comment by hthetiot** [comment]
confirm `2.4.4+dfsg-4.pgdg90+1`

**Comment by md5** [comment]
Sorry to bug you @tianon, but do you have any idea why we would be seeing this error on the Debian-based images:

> /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/postgis.sh
/docker-entrypoint-initdb.d/postgis.sh: 9: /docker-entrypoint-initdb.d/postgis.sh: Bad substitution
failed

Looks like something is off with the `$psql` variable?

https://github.com/appropriate/docker-postgis/blob/76fee7e/initdb-postgis.sh#L17

**Comment by md5** [comment]
I'm going to see if combining the change from @jjmata in #99 into this branch will work. I'm pushing it as a separate branch right now.

**Comment by jjmata** [comment]
That was the error I fixed by simply removing the execute bit, yes!  Glad it came in handy here ...

**Comment by md5** [comment]
I should have looked more closely at the commit you referenced, https://github.com/docker-library/postgres/commit/eff90effc6b5578be90bef93d96b3fceb1082a7c

I think the actual problem with `$psql` may be that it isn't being exported, so it fails when you exec the  script instead of sourcing it. Either that or it has to do with incompatibility between array variables and child processes.

**Comment by jjmata** [comment]
The code in that commit is careful to source files with no execute bit, and fork those that have it.  It worked for me in my fork to just remove the exec bit.

**Pull request merged**
