### PR TITLE
Ensure that postgres is the first init script.

### PR DESCRIPTION
**Pull request by Joxit**
You can order more easily your scripts with the norm `00-name` and the alphabetical order.

### CODE REVIEW

**Comment by md5** [comment]
While I can see your concern here, this could be a breaking change for existing users who are relying on the current order.

Wouldn't it be fine to call your scripts `postgis-*.sh`? That should be enough to ensure they run later.

**Comment by Joxit** [comment]
Ok, that is fine. It was to introduce naming conventions in your docker image. :)

Nope, because `-` is less than `.` (in ASCII table) so `postgis.sh` will be run before `postgis-*.sh`.

**Comment by md5** [comment]
Looks like underscore would work, then. I think it may be good to document this.

**Comment by Joxit** [comment]
Ok, thx, I close the PR then :)

**Pull request closed without merging**
