### PR TITLE
Remove 9.1, add 9.6, update all to postgis 2.3

### LINKED ISSUE #40: Please add postgresql 9.6 with postGIS 2.3
Can you please add a branch for postgresql 9.6 with postGIS 2.3?

Cheers
CGD

### PR DESCRIPTION
**Pull request by JacobHayes**
Resolves #40

### CODE REVIEW

**Comment by jjmata** [comment]
Thanks for putting this together, @JacobHayes!  Please update https://github.com/appropriate/docker-postgis/blob/master/.travis.yml#L7 for the automated tests to build ...

**Comment by md5** [comment]
Thanks @JacobHayes! I should have checked my notifications more closely before opening #42

**Comment by md5** [comment]
I wish there were a way to make `.travis.yml` run a command to determine the build matrix to avoid having to update it for each version update.

**Comment by md5** [comment]
Looks like dynamic build matrixes have been discussed here, but it isn't a planned feature: https://github.com/travis-ci/travis-ci/issues/2568

**Pull request merged**
