### PR TITLE
add missing libprotobuf-c to alpine #71

### PR DESCRIPTION
**Pull request by stepankuzmin**
...according to #71

### CODE REVIEW

**Comment by md5** [comment]
I'll need the PR to update `Dockerfile.alpine.template` and the other directories as well, since your changes will be wiped out by the next `make update` otherwise.

**Comment by md5** [comment]
BTW, the build should fail if you rebase against `master` once I merge #82.

**Comment by stepankuzmin** [comment]
Thanks for the feedback, I've updated the PR.

**Comment by md5** [comment]
Can you actually run `make update` to update the other Dockerfiles?

**Comment by stepankuzmin** [comment]
Done!

**Pull request merged**
